# Generated by Django 3.2.6 on 2021-08-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=models.CharField(choices=[('choice3', 'Choice3'), ('choice1', 'Choice1'), ('choice2', 'Choice2')], default='', max_length=20),
        ),
    ]
