# Generated by Django 3.2.6 on 2021-08-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='interest',
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=models.ManyToManyField(related_name='CustomUser', to='users.Interest'),
        ),
    ]
