# Generated by Django 3.2.6 on 2021-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210824_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='CustomUser', to='users.Interest'),
        ),
    ]
