# Generated by Django 3.2.5 on 2021-07-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210704_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('DIY/공구', 'DIY/공구'), ('홈데코/조명', '홈데코/조명'), ('가구', '가구'), ('수납/정리', '수납/정리'), ('패브릭', '패브릭'), ('가전', '가전')], max_length=20),
        ),
    ]
