# Generated by Django 3.2.6 on 2021-08-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20210704_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('가구', '가구'), ('패브릭', '패브릭'), ('수납/정리', '수납/정리'), ('DIY/공구', 'DIY/공구'), ('가전', '가전'), ('홈데코/조명', '홈데코/조명')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
