# Generated by Django 3.2.6 on 2021-08-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210819_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('장식/조명', '장식/조명'), ('패브릭', '패브릭'), ('수납/정리', '수납/정리'), ('가구', '가구'), ('가전', '가전'), ('DIY/공구', 'DIY/공구')], default='가구', max_length=20),
        ),
    ]
