# Generated by Django 3.2.6 on 2021-08-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210819_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_Type',
            field=models.CharField(choices=[('비매품', '비매품'), ('온라인', '온라인'), ('오프라인', '오프라인')], default='온라인', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('DIY/공구', 'DIY/공구'), ('패브릭', '패브릭'), ('수납/정리', '수납/정리'), ('가전', '가전'), ('장식/조명', '장식/조명'), ('가구', '가구')], default='가구', max_length=20),
        ),
        migrations.AlterField(
            model_name='product_comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='product.product'),
        ),
    ]
