# Generated by Django 3.2.6 on 2021-08-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('가구', '가구'), ('수납/정리', '수납/정리'), ('가전', '가전'), ('패브릭', '패브릭'), ('DIY/공구', 'DIY/공구'), ('홈데코/조명', '홈데코/조명')], max_length=20),
        ),
    ]
