# Generated by Django 3.2.6 on 2021-08-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210818_1948'),
        ('curation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curation',
            name='products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='curation', to='product.product'),
        ),
    ]
