# Generated by Django 3.2.6 on 2021-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210818_2016'),
        ('curation', '0002_curation_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curation',
            name='products',
        ),
        migrations.AddField(
            model_name='curation',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
