# Generated by Django 3.2.6 on 2021-08-19 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0003_auto_20210818_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curation_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('curation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curation_comments', to='curation.curation')),
            ],
        ),
    ]
