# Generated by Django 3.2.6 on 2021-08-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0004_curation_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Curation_comment',
            new_name='CurationComment',
        ),
    ]
