# Generated by Django 3.2.6 on 2021-08-23 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curation', '0006_curation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='curation',
            name='product_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
